#!/usr/bin/env bash
# Bootstrap local-llm on macOS: Ollama + Go binary + API key + tiny smoke-test model.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

echo "==> repo: $ROOT"

if ! command -v brew >/dev/null 2>&1; then
  echo "Homebrew is required. Install from https://brew.sh" >&2
  exit 1
fi

if ! command -v go >/dev/null 2>&1; then
  echo "==> installing Go via Homebrew"
  brew install go
fi

if ! command -v ollama >/dev/null 2>&1; then
  echo "==> installing Ollama via Homebrew"
  brew install ollama
fi

echo "==> ensuring Ollama is running (localhost only — never OLLAMA_HOST=0.0.0.0)"
if ! curl -sf "http://127.0.0.1:11434/api/tags" >/dev/null 2>&1; then
  if brew services list 2>/dev/null | awk '$1=="ollama"{found=1} END{exit !found}'; then
    brew services start ollama || true
  elif command -v open >/dev/null 2>&1 && [[ -d /Applications/Ollama.app ]]; then
    open -a Ollama || true
  else
    OLLAMA_HOST=127.0.0.1:11434 nohup ollama serve >/tmp/ollama-serve.log 2>&1 &
  fi
  echo "    waiting for Ollama on 127.0.0.1:11434 …"
  for _ in $(seq 1 60); do
    if curl -sf "http://127.0.0.1:11434/api/tags" >/dev/null 2>&1; then
      break
    fi
    sleep 1
  done
fi

if ! curl -sf "http://127.0.0.1:11434/api/tags" >/dev/null 2>&1; then
  echo "Ollama did not become ready on 127.0.0.1:11434" >&2
  echo "Try: open -a Ollama   or   OLLAMA_HOST=127.0.0.1:11434 ollama serve" >&2
  exit 1
fi
echo "    Ollama is up"

if [[ ! -f "$ROOT/.env" ]]; then
  KEY="$(openssl rand -hex 32)"
  cat > "$ROOT/.env" <<EOF
# Generated by scripts/setup.sh — do not commit
LOCAL_LLM_API_KEY=${KEY}
EOF
  chmod 600 "$ROOT/.env"
  echo "==> wrote .env with a new LOCAL_LLM_API_KEY"
else
  echo "==> .env already exists (leaving key unchanged)"
fi

TINY_MODEL="smollm2:135m"
echo "==> pulling smoke-test model: ${TINY_MODEL}"
if ! ollama pull "$TINY_MODEL"; then
  echo "    ${TINY_MODEL} pull failed; trying smollm2:360m …" >&2
  TINY_MODEL="smollm2:360m"
  ollama pull "$TINY_MODEL"
  # Keep config in sync if we fell back.
  if grep -q 'smollm2:135m' "$ROOT/config/models.yaml"; then
    sed -i '' "s/smollm2:135m/${TINY_MODEL}/" "$ROOT/config/models.yaml"
    echo "    updated config/models.yaml upstream to ${TINY_MODEL}"
  fi
fi

echo "==> building gateway"
mkdir -p "$ROOT/bin"
go build -o "$ROOT/bin/local-llm" "$ROOT/cmd/local-llm"

# shellcheck disable=SC1091
source "$ROOT/.env"
LAN_IP="$(ipconfig getifaddr en1 2>/dev/null || ipconfig getifaddr en0 2>/dev/null || echo "<your-mac-lan-ip>")"

cat <<EOF

Setup complete.

Start the gateway:
  make run
  # or: ./bin/local-llm serve --config config/models.yaml --env-file .env

Test locally:
  curl http://127.0.0.1:4000/v1/models \\
    -H "Authorization: Bearer \$LOCAL_LLM_API_KEY"

  curl http://127.0.0.1:4000/v1/chat/completions \\
    -H "Authorization: Bearer \$LOCAL_LLM_API_KEY" \\
    -H "Content-Type: application/json" \\
    -d '{"model":"tiny","messages":[{"role":"user","content":"Say hi in five words."}]}'

From another device on your LAN (API key from .env):
  curl http://${LAN_IP}:4000/v1/chat/completions \\
    -H "Authorization: Bearer <LOCAL_LLM_API_KEY>" \\
    -H "Content-Type: application/json" \\
    -d '{"model":"tiny","messages":[{"role":"user","content":"Say hi in five words."}]}'

Security reminders:
  - Keep Ollama on 127.0.0.1 only (do not set OLLAMA_HOST=0.0.0.0)
  - Do not port-forward 4000 or 11434 to the internet
  - Keep .env private

macOS firewall (needed for other devices on the LAN):
  make allow-firewall

Optional auto-start at login:
  make install-launchd
EOF
